'use client'

import { useMemo, useState } from 'react'
import {
  ArrowRight, Check, Heart, Menu, Moon, PackageCheck,
  Phone, Search, ShoppingBag, Sparkles, Sun, Truck, UserRound,
} from 'lucide-react'

const categories = ['All Products', 'Offers', 'Sunscreen', 'Facewash', 'Face Serum', 'Cream', 'Shampoo', 'Jewelry', 'Baby Care']
const products = [
  { brand: 'The Body Shop', name: 'Shea Body Butter', size: '200ml', category: 'Cream', price: 1650, old: 1900, tone: 'body', batch: 'TBS-UK-24A', tag: 'Bestseller' },
  { brand: 'Boots Soltan', name: 'Protect & Moisturise SPF 50+', size: '200ml', category: 'Sunscreen', price: 1850, old: 2200, tone: 'sun', batch: 'SOL-UK-88F', tag: 'Save 16%' },
  { brand: 'CeraVe', name: 'Hydrating Cleanser', size: '236ml', category: 'Facewash', price: 2150, old: 2400, tone: 'cleanse', batch: 'CER-UK-19Q', tag: 'UK Import' },
  { brand: 'The Ordinary', name: 'Niacinamide 10% + Zinc 1%', size: '30ml', category: 'Face Serum', price: 1750, old: 1990, tone: 'serum', batch: 'ORD-UK-72C', tag: 'Trending' },
  { brand: 'Aveeno', name: 'Daily Moisturising Lotion', size: '300ml', category: 'Cream', price: 1950, old: 2250, tone: 'lotion', batch: 'AVE-UK-42P', tag: 'UK Import' },
  { brand: 'Johnson’s', name: 'Baby Bedtime Wash', size: '500ml', category: 'Baby Care', price: 1250, old: 1450, tone: 'baby', batch: 'JOH-UK-61B', tag: 'Gentle care' },
]
const money = (value: number, gbp: boolean) => gbp ? `£${(value / 150).toFixed(2)}` : `৳${value.toLocaleString('en-BD')}`

function ProductVisual({ tone }: { tone: string }) {
  return <div className={`product-visual visual-${tone}`} aria-hidden="true"><div className="bottle-cap" /><div className="bottle"><span>UK<br /><b>BRAND</b></span></div><div className="leaf leaf-one" /><div className="leaf leaf-two" /></div>
}



export default function Page() {
  const [dark, setDark] = useState(false), [gbp, setGbp] = useState(false), [category, setCategory] = useState('All Products'), [query, setQuery] = useState(''), [cart, setCart] = useState(0), [liked, setLiked] = useState<string[]>([])
  const filtered = useMemo(() => products.filter(p => (category === 'All Products' || category === 'Offers' ? true : p.category === category) && `${p.brand} ${p.name}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  const add = (name: string) => { setCart(n => n + 1); if (!liked.includes(name)) setLiked(liked) }
  return <div className={dark ? 'storefront dark-mode' : 'storefront'}>
    <div className="utility"><span>01959-524393 <i>|</i> Order via Call or WhatsApp</span><span className="ticker">Free delivery in Dhaka on orders over ৳5,000</span><span className="utility-actions"><button onClick={() => setGbp(false)} className={!gbp ? 'active' : ''}>BDT ৳</button><button onClick={() => setGbp(true)} className={gbp ? 'active' : ''}>GBP £</button><button onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={15} /> : <Moon size={15} />}</button></span></div>
    <header><div className="main-header"><button className="mobile-menu" aria-label="Open menu"><Menu size={21} /></button><div className="wordmark"><h1>UK Brand Lover</h1><span>London to Dhaka</span></div><div className="search"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search Boots, Cetaphil, CeraVe..." /></div><nav className="header-actions"><button aria-label="Account"><UserRound size={19} /></button><button aria-label="Wishlist"><Heart size={19} /></button><button className="cart" aria-label="Cart"><ShoppingBag size={19} /><b>{cart}</b></button></nav></div><div className="category-scroll">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={category === item ? 'selected' : ''}>{item}</button>)}</div></header>
    <main>
      <section className="hero"><div className="hero-copy"><span className="eyebrow">Genuinely sourced <i>•</i> London to Dhaka</span><h2>British shelf staples,<br /><em>flown in</em> — not knocked off.</h2><p>Authentic beauty and personal care, picked from trusted stores like Boots and Superdrug, then air-freighted to your door in Dhaka.</p><div className="hero-buttons"><button className="button button-dark" onClick={() => document.getElementById('collection')?.scrollIntoView({ behavior: 'smooth' })}>Shop collection <ArrowRight size={16} /></button><a className="button button-outline" href="https://facebook.com/tuhinatopa" target="_blank" rel="noreferrer">Visit Facebook page</a></div><div className="hero-signature"><span>UK</span><p>Personal imports,<br />properly verified.</p></div></div><div className="hero-product"><div className="verification"><Check size={14} /> Batch verified<br /><strong>Authentic UK import</strong></div><ProductVisual tone="sun" /><div className="hero-product-caption"><span>Featured edit</span><strong>Boots Soltan<br />Protect & Moisturise SPF 50+</strong><small>{money(1850, gbp)}</small></div></div></section>
      <section className="trust-row"><div><Truck size={21} /><span><strong>Free Dhaka delivery</strong>Over ৳5,000</span></div><div><PackageCheck size={21} /><span><strong>100% verified imports</strong>Every item batch-checked</span></div><div><Phone size={21} /><span><strong>Order via WhatsApp / call</strong>01959-524393</span></div><div><Sparkles size={21} /><span><strong>2,000+ verified reviews</strong>On Facebook</span></div></section>
      <section className="offers"><div><span className="eyebrow">The good stuff, together</span><h2>Current offers <em>& bundles</em></h2><p>Thoughtfully paired British favourites, priced to make your routine feel a little more considered.</p></div><button className="button button-light" onClick={() => { setCategory('Offers'); document.getElementById('collection')?.scrollIntoView({ behavior: 'smooth' }) }}>Explore offers <ArrowRight size={16} /></button></section>
      <section id="collection" className="collection"><div className="section-heading"><div><span className="eyebrow">The current edit</span><h2>Made for your <em>shelf.</em></h2></div><span className="result-count">{filtered.length} products</span></div><div className="product-grid">{filtered.map(p => <article className="product-card" key={p.name}><div className="product-image-wrap"><span className="import-tag">UK Import</span><span className="save-tag">{p.tag}</span><button className={`heart-button ${liked.includes(p.name) ? 'liked' : ''}`} onClick={() => setLiked(liked.includes(p.name) ? liked.filter(n => n !== p.name) : [...liked, p.name])} aria-label="Add to wishlist"><Heart size={17} fill={liked.includes(p.name) ? 'currentColor' : 'none'} /></button><ProductVisual tone={p.tone} /><div className="quick-actions"><button onClick={() => add(p.name)}>Quick add to cart</button></div></div><div className="product-info"><span>{p.brand}</span><h3>{p.name}</h3><small>{p.size} · {p.category}</small><div><strong>{money(p.price, gbp)}</strong><del>{money(p.old, gbp)}</del></div></div></article>)}</div>{filtered.length === 0 && <div className="empty">No pieces found. Try a different search.</div>}</section>
      <section className="story-grid"><div className="story-card"><span className="eyebrow">Our little beginning</span><h2>Started on Facebook.<br /><em>Still run that way.</em></h2><p>What began as personal suitcase imports for friends became a trusted Dhaka destination for the British beauty staples we kept reaching for ourselves.</p><a href="https://facebook.com/tuhinatopa" target="_blank" rel="noreferrer">Read our story <ArrowRight size={16} /></a></div><div className="social-card"><Sparkles size={20} /><span className="eyebrow">Follow the real-time edit</span><h3>@ukbrandlover</h3><p>New arrivals, suitcase reveals, and honest reviews from our community in Bangladesh.</p><strong>2,000+ <small>Followers on Facebook</small></strong><a href="https://facebook.com/tuhinatopa" target="_blank" rel="noreferrer" className="button button-outline">Visit Facebook page</a></div></section>
    </main><footer><div className="wordmark"><h1>UK Brand Lover</h1><span>London to Dhaka</span></div><p>Authentic British beauty, closer to home.</p><span>© 2026 UK Brand Lover · Dhaka, Bangladesh</span></footer>
  </div>
}
